spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://ec2-23-21-177-102.compute-1.amazonaws.com:5432/d5si7ggkonfqer?ssl=false&sslfactory=org.postgresql.ssl.NonValidatingFactory
    driver-class-name: org.postgresql.Driver
    username: xghpnrdyxfcayb
    password: 9e7f6af61fb711007d545440da727d9c1a62bc15cf3d4ce18998d1bd51cfa15e

  logging:
    level:
      root: INFO
  file: heroapi.log